Added error handling around wrong/missing arguments

diff --git a/docs/modules/getting_started/examples/code/getting-started.sh.j2 b/docs/modules/getting_started/examples/code/getting-started.sh.j2
--- a/docs/modules/getting_started/examples/code/getting-started.sh.j2
+++ b/docs/modules/getting_started/examples/code/getting-started.sh.j2
@@ -11,6 +11,12 @@ set -euo pipefail
 # The script can be run as a test as well, to make sure that the tutorial works
 # It includes some assertions throughout, and at the end especially.
 
+if [ $# -eq 0 ]
+then
+  echo "Installation method argument ('helm' or 'stackablectl') required."
+  exit 1
+fi
+
 case "$1" in
 "helm")
 echo "Adding '{{ helm.repo_name }}' Helm Chart repository"
@@ -36,6 +42,10 @@ stackablectl operator install \
   hdfs={{ versions.hdfs }} \
   druid={{ versions.druid }}
 # end::stackablectl-install-operators[]
+;;
+*)
+echo "Need to give 'helm' or 'stackablectl' as an argument for which installation method to use!"
+exit 1
 ;;
 esac
 
